# Generated by Django 2.1.2 on 2018-11-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='UserName',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='UserPwd',
            field=models.CharField(max_length=24),
        ),
    ]
